# Generated by Django 2.0 on 2019-05-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_long', models.URLField(max_length=500, unique=True)),
                ('url_short', models.CharField(max_length=8, unique=True)),
            ],
        ),
    ]
